[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
settler = "AcyeAq69xe7JV4F9uwpWzPgyxbxxYUALnYfeMsaDauGR"
controller = "DL2RrwABRChbMFawCu5tGZ6VavM3RZgiGHEbu7PP47fK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json tests/*.ts"
