name: CI EVM

env:
  CI: true

on:
  push:
    branches: "*"
    paths:
      - packages/evm/**
  pull_request:
    branches: "*"
    paths:
      - packages/evm/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        working-directory: packages/evm
        run: yarn
      - name: Build
        working-directory: packages/evm
        run: yarn build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        working-directory: packages/evm
        run: yarn
      - name: Build
        working-directory: packages/evm
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        working-directory: packages/evm
        run: yarn
      - name: Build
        working-directory: packages/evm
        run: yarn build
      - name: Test
        working-directory: packages/evm
        run: yarn test
